"""Add SimulationNeed model

Revision ID: 1433d60bd29d
Revises: e96b0c9255e2
Create Date: 2026-04-22 00:58:16.591278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1433d60bd29d'
down_revision: Union[str, Sequence[str], None] = 'e96b0c9255e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation_needs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('urgency', sa.String(), nullable=True),
    sa.Column('need_type', sa.String(), nullable=True),
    sa.Column('people_affected', sa.Integer(), nullable=True),
    sa.Column('is_simulation', sa.Boolean(), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_needs_id'), 'simulation_needs', ['id'], unique=False)
    op.create_index(op.f('ix_simulation_needs_location'), 'simulation_needs', ['location'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulation_needs_location'), table_name='simulation_needs')
    op.drop_index(op.f('ix_simulation_needs_id'), table_name='simulation_needs')
    op.drop_table('simulation_needs')
    # ### end Alembic commands ###
